(("spacemacs" . ((user-emacs-directory . "~/.config/emacs/spacemacs/.emacs.d")))
 ("prelude"   . ((user-emacs-directory . "~/.config/emacs/prelude/.emacs.d")))
 ("jlv"       . ((user-emacs-directory . "~/.config/emacs/jlv/.emacs.d")))
 ("default"   . ((user-emacs-directory . "~/.config/emacs/doom/.emacs.d")
                 (env . (("EMACSDIR"   . "~/.config/emacs/doom/.emacs.d")
		                 ("DOOMDIR"    . "~/.config/emacs/doom/.doom.d"))))))
